# Generated by Django 5.0.7 on 2024-08-13 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_doctor_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnostic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=150)),
                ('mobile', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('sample_date', models.DateField()),
                ('sample_time', models.TimeField()),
                ('report_date', models.DateField()),
                ('report_time', models.TimeField()),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('due', models.DecimalField(decimal_places=2, max_digits=10)),
                ('doctor_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnostics', to='home.doctor')),
            ],
        ),
    ]
