# Generated by Django 5.0.7 on 2024-08-13 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_diagnostic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diagnostic',
            old_name='doctor_id',
            new_name='doctor',
        ),
    ]
