# Generated by Django 5.0.7 on 2024-08-15 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_rename_doctor_id_diagnostic_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnostic',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
