# Generated by Django 5.0.7 on 2024-08-17 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='species',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(max_length=20),
        ),
    ]
